### PR TITLE
Performance Issues

### PR DESCRIPTION
**Pull request by bdonahue**
Fixes library performance issues.

I don't submit to open source often, don't know if I am doing the pull correctly. Just want it to say aligned with the first review but it probably wont.

### CODE REVIEW

**Comment by tprochazka** [comment]
I red also discussion at candrews/HttpResponseCache#19 ans I think that it should be really fixed, but I only don't think that is neccesary to pool 10 instances. I think that 3 will be enough.

**Comment by tprochazka** [comment]
And I found that this solution is not enough. If you use cookies, class `HTTPCookie` use this `Date date = HttpDate.parse(value);` on the line 327. But date format in cookies is `Wdy, DD-Mon-YY HH:MM:SS GMT` (RFC RFC 1036 according http://www.ietf.org/rfc/rfc2109.txt), so there are "-" instead of space. So your pool will be skipped and `new SimpleDateFormat` will be still called for every request :-(

So two pools is necessary if cookie is using.
And best would be pools with lazy initialization where new parser will be created only if all are currently in use.

**Comment by tprochazka** [comment]
And because I have `HTTPCookie` backported in my code to use it on older Android I did this dirty hack:
`Date date = HttpDate.parse(value.replace("-"," "));`

**Comment by tprochazka** [comment]
I also found that use default implementation is not so big problem if you use AsyncTask, AsyncTaskLoader or any custom service thread, because it keep thread alive so it also cache SimpleDateFormat and doesn't create too much instances during app running.

**Comment by bdonahue** [comment]
That is true, so long as you keep the thread alive and use that existing thread to download your next HTTP request then you will not run into this bottleneck.

**Pull request closed without merging**
