### PR TITLE
ISSUE-3: SimpleDateFormat can be extremely slow to parse

### PR DESCRIPTION
**Pull request by bdonahue**
This ticket description is actually somewhat off as far as what the real issue is here.
I used the Android performance analysis tool to discover the real issue is these two lines:

new SimpleDateFormat("EEE, dd MMM yyyy HH:mm:ss zzz", Locale.US);
TimeZone.getTimeZone("UTC")

The root of the issue is that DateFormat is not thread safe, and is very slow to create.
I used the performance analysis tool to try a few approaches to solve the
issue and measure which was most performant. First I tried a simple synchronized access
to a single class wide copy of this variable. For an average test case of about 10 concurrent
downloads this increased the performance to ~5.4 times faster then the baseline. There was now
however a good amount of delay introduced by waiting for the synchronization. So an alternative
approach was tried where a pool of SimpleDateFormat's is created which can be used and recycled
back into the pool. With this approach the performance is now ~10.4 times faster. When I was
analyzing the performance this was by far the single most time consuming task, the entire
library is much faster as a result of this patch.

### CODE REVIEW

**Comment by jaypatrickhoward** [comment]
Is my clone() idea garbage?  (It may well be; this is an honest question).  Create a single static instance and just have each thread clone a copy for its own use instead of instantiating a new one via the SimpleDateFormat(String, Locale) constructor.

**Comment by bdonahue** [comment]
Tried it, clone was really slow. I would prefer a more simple solution like that myself.

**Comment by jaypatrickhoward** [comment]
How about lazily instantiating a ThreadLocal copy (or re-using the existing copy if one already exists)?  Or are we worried about leaking these since threads are pooled...

**Comment by bdonahue** [comment]
You can try whatever else you want, this works great. I am not spending any more time on it.

**Comment by jaypatrickhoward** [comment]
Just realized the ThreadLocal approach was what the code was already doing.

Might be worth a look at FastDateFormat from commons lang assuming it ports to Android and there aren't license issues.  It's thread-safe and apparently much more optimized than the stock SimpleDateFormat.

http://commons.apache.org/lang/api-release/org/apache/commons/lang3/time/FastDateFormat.html

**Comment by candrews** [comment]
@jaypatrickhoward  The Apache Commons FastDateFormat was a really neat idea - it's existing, well tested, well written code under an acceptable/compatible license - but it only does formatting, and doesn't do parsing, and parsing is a significant use case in this library.

**Comment by candrews** [comment]
BTW - this is to workaround this issue: https://code.google.com/p/android/issues/detail?id=3147

**Comment by candrews** [comment]
It appears this issue exists until at least Android 3.0... do you happen to know if it still exists in 4.0 or 4.1?

**Comment by jaypatrickhoward** [comment]
The DateUtils class in commons-lang has parsing functionality.

http://commons.apache.org/lang/api-release/org/apache/commons/lang3/time/DateUtils.html

Unfortunately it looks like it uses SimpleDateFormat under the covers.  Is it necessary to specify a Locale and TimeZone for _parsing_ as well as for formatting?

**Comment by candrews** [comment]
@jaypatrickhoward Locale definitely - a locale could use a non-Gregorian calendar, and that would really ruin your day

**Comment by candrews** [comment]
@bdonahue I added some comments / review points to your commit. I _think_ this issue is fixed in ICS. If it is, then it would be great if we could figure out a way to only use your (very neat!) SimpleDateFormat pool on Android < ICS, and use the (as close to) unmodified original code as possible for Android >= ICS. I'm psyched about getting this in - it should be a big win for users of this library.

**Comment by iNoles** [comment]
I took a peek to SimpleDateFormat.java on Android 4.1.1, I found libcore.icu.LocaleData and libcore.icu.TimeZones;

**Comment by candrews** [comment]
@iNoles okay... what is the significance of that discovery? :)

**Comment by jaypatrickhoward** [comment]
Is syncrhonizing on a single static instance really so much slower that it's worth adding the complexity of a SimpleDateFormat pool?  In the scope of a HTTP request over the network I can't imagine the the time needed to parse or format a date (note: not the initial load time but the time required to actually parse/format) would be so significant as to result in much contention.

If we had ten threads making HTTP requests in a tight loop, how often do we think one would block waiting to synchronize on a static SimpleDateFormat instance?  I'm thinking "not often" and "not for very long even when it does happen".

**Comment by bdonahue** [comment]
@candrews Thanks for taking the time to leave me feedback. Good question about the ICS and Jellybean. I have access to a virtually unlimited number of devices so I gave this a try before and after on two identical ICS devices, and two identical Jellybean devices. On both there is still a dramatic performance gain, although not nearly as dramatic as on older phones. I believe it is CPU limited, which is why the older phones perform so much worse. On a Jellybean Galaxy nexus this speeds up downloads by an average of about half a second, on older more average 2.3 phones (Which is about 70% of the user base of most apps) it speeds up downloads by about 8 seconds.

**Pull request closed without merging**
